### ISSUE TITLE
send函数的可靠性不够

### ISSUE THREAD

**Issue by laomoi** [XINCGer/Cocos2d-X_Tools#1]
int ODSocket::Send(const char* buf, int len, int flags)
{
	int bytes;
	int count = 0;

	while ( count < len ) {

		bytes = send(m_sock, buf + count, len - count, flags);
		if ( bytes == -1 || bytes == 0 )
			return -1;
		count += bytes;
	} 

	return count;
}

如果是blocking的socket, 用while循环有啥意义？

如果是none blocking的socket, send返回-1的时候，如果error no 是EGAIN， 那可以在循环里重试吧？如果直接返回-1， 调用者也不知道已经发送了多少数据， 也没办法补发后面的数据。

**Comment by XINCGer** [comment]
嗯，是的，这个是当时学习Cocos2d-x的时候弄得一个第三方网络库，现在很久没用这玩意了。
